---
- name: pip modules to secure access to Ansible Galaxy
  pip:
    name: "{{ item }}"
    executable: "{{ '/opt/pyenv/shims/pip' if ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' else omit }}"
  with_items:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1

- name: deploy ansistrano
  command: "{{ '/opt/pyenv/shims/'  if ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' else '' }}ansible-galaxy install ansistrano.deploy ansistrano.rollback"
  become_user: "{{ roles_common_deploy_user }}"
